name: Unit tests on branches

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'src/**'
      - 'pom.xml'
      - 'Dockerfile'
      - '.mvn/**'
      - 'mvnw'
      - 'mvnw.cmd'
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run unit tests
        run: mvn test -Dtest="es.codeurjc.unit.*Test"
